version: '3.1'
services:
  dev-ibp:
    build: ./node
    container_name: dev-ibp
    ports:
      - '3105:3000'
    user: node
    volumes:
      - './app:/app'
    working_dir: /app
    tty: true
    environment:
      - API_URL=${API_URL}
    networks:
      dockernet: null
#    command: yarn start
networks:
  dockernet:
    external:
      name: dockernet
